name: Build from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Make tag
        run: echo "::set-env name=TAG_NAME::$(echo $GITHUB_REF | awk -F / '{print $3}')-${GITHUB_HEAD_REF##*/}"
      - name: Build
        uses: metal-stack/action-docker-make@master
        with:
          args: >
            --no-cache
            --build-only cloudctl-slug
            --no-push
            -x rule2,rule3
            --summary
      - name: Prepare upload
        run: |
          mkdir -p cloudctl/pull-requests/${TAG_NAME}
          sudo chown -R $(id -u):$(id -g) result
          mv result/* cloudctl/pull-requests/${TAG_NAME}
      - name: Upload image tarballs to GCS
        run: gsutil -m cp -r -p cloudctl gs://$GCS_BUCKET
    