name: release

on:
  release:
    types:
      - published

env:
  GCS_BUCKET: images.metal-pod.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Make tag
        run: echo "::set-env name=TAG_NAME::${GITHUB_REF##*/}"
      - name: Build
        uses: metal-stack/action-docker-make@master
        with:
          args: >
            --no-cache
            --no-push
            --build-only cloudctl-slug
            -x rule2,rule3
            --summary
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: result/cloudctl-linux-amd64
          asset_name: cloudctl-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: result/cloudctl-windows-amd64
          asset_name: cloudctl-windows-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: result/cloudctl-darwin-amd64
          asset_name: cloudctl-darwin-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: result/cloudctl-linux-amd64.md5
          asset_name: cloudctl-linux-amd64.md5
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: result/cloudctl-windows-amd64.md5
          asset_name: cloudctl-windows-amd64.md5
          asset_content_type: application/octet-stream
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: result/cloudctl-darwin-amd64.md5
          asset_name: cloudctl-darwin-amd64.md5
          asset_content_type: application/octet-stream
